// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotionSearchFilter } from "./NotionSearchFilter";
import type { NotionSortDirection } from "./NotionSortDirection";

export type NotionSearchInput = { query: string | null, filter: NotionSearchFilter | null, sort_direction: NotionSortDirection | null, start_cursor: string | null, page_size: number | null, };
