// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotionSearchOutput = { results: any[], next_cursor: string | null, has_more: boolean, };
